language: android
jdk: oraclejdk8
sudo: false
android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
    - extra

    # Additional components
    #- extra-google-google_play_services
    #- addon-google_apis-google-19

    # Specify at least one system image, if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-19
    #- sys-img-x86-android-17

  licenses:
    - '.+'

before_install:
  - yes | sdkmanager "platforms;android-27"
  - chmod a+x gradlew

script:
#  - ./gradlew clean build
 - ./gradlew :app:assembleRlsRelease

deploy:
  provider: releases
  api_key:
    secure: 76365c9e32d539cb342ecc9100e81c9ee8e9c525
  file: app/build/outputs/apk/rls/release/app-rls-release.apk
  on:
    repo: firelotus/Meteorite
    tags: true
    all_branches: true
before_install:
- gem install fir-cli
after_deploy:
- fir p app/build/outputs/apk/rls/release/app-rls-release.apk -T $FIR_TOKEN -c "`git cat-file tag $TRAVIS_TAG`"